import { createContext, useContext, useState } from "react";

const SongContext = createContext();
const initialSong1Data = {
  album: {
    album_type: "album",
    artists: [
      {
        external_urls: {
          spotify: "https://open.spotify.com/artist/3qm84nBOXUEQ2vnTfUTTFC",
        },
        href: "https://api.spotify.com/v1/artists/3qm84nBOXUEQ2vnTfUTTFC",
        id: "3qm84nBOXUEQ2vnTfUTTFC",
        name: "Guns N' Roses",
        type: "artist",
        uri: "spotify:artist:3qm84nBOXUEQ2vnTfUTTFC",
      },
    ],
    available_markets: [
      "AR",
      "AU",
      "AT",
      "BE",
      "BO",
      "BR",
      "BG",
      "CA",
      "CL",
      "CO",
      "CR",
      "CY",
      "CZ",
      "DK",
      "DO",
      "DE",
      "EC",
      "EE",
      "SV",
      "FI",
      "FR",
      "GR",
      "GT",
      "HN",
      "HK",
      "HU",
      "IS",
      "IE",
      "IT",
      "LV",
      "LT",
      "LU",
      "MY",
      "MT",
      "MX",
      "NL",
      "NZ",
      "NI",
      "NO",
      "PA",
      "PY",
      "PE",
      "PH",
      "PL",
      "PT",
      "SG",
      "SK",
      "ES",
      "SE",
      "CH",
      "TW",
      "TR",
      "UY",
      "US",
      "GB",
      "AD",
      "LI",
      "MC",
      "ID",
      "JP",
      "TH",
      "VN",
      "RO",
      "IL",
      "ZA",
      "SA",
      "AE",
      "BH",
      "QA",
      "OM",
      "KW",
      "EG",
      "MA",
      "DZ",
      "TN",
      "LB",
      "JO",
      "PS",
      "IN",
      "BY",
      "KZ",
      "MD",
      "UA",
      "AL",
      "BA",
      "HR",
      "ME",
      "MK",
      "RS",
      "SI",
      "KR",
      "BD",
      "PK",
      "LK",
      "GH",
      "KE",
      "NG",
      "TZ",
      "UG",
      "AG",
      "AM",
      "BS",
      "BB",
      "BZ",
      "BT",
      "BW",
      "BF",
      "CV",
      "CW",
      "DM",
      "FJ",
      "GM",
      "GE",
      "GD",
      "GW",
      "GY",
      "HT",
      "JM",
      "KI",
      "LS",
      "LR",
      "MW",
      "MV",
      "ML",
      "MH",
      "FM",
      "NA",
      "NR",
      "NE",
      "PW",
      "PG",
      "WS",
      "SM",
      "ST",
      "SN",
      "SC",
      "SL",
      "SB",
      "KN",
      "LC",
      "VC",
      "SR",
      "TL",
      "TO",
      "TT",
      "TV",
      "VU",
      "AZ",
      "BN",
      "BI",
      "KH",
      "CM",
      "TD",
      "KM",
      "GQ",
      "SZ",
      "GA",
      "GN",
      "KG",
      "LA",
      "MO",
      "MR",
      "MN",
      "NP",
      "RW",
      "TG",
      "UZ",
      "ZW",
      "BJ",
      "MG",
      "MU",
      "MZ",
      "AO",
      "CI",
      "DJ",
      "ZM",
      "CD",
      "CG",
      "IQ",
      "LY",
      "TJ",
      "VE",
      "ET",
      "XK",
    ],
    external_urls: {
      spotify: "https://open.spotify.com/album/0suNLpB9xraAv1FcdlITjQ",
    },
    href: "https://api.spotify.com/v1/albums/0suNLpB9xraAv1FcdlITjQ",
    id: "0suNLpB9xraAv1FcdlITjQ",
    images: [
      {
        height: 640,
        url: "https://i.scdn.co/image/ab67616d0000b273e29a351729da4d29214e54e2",
        width: 640,
      },
      {
        height: 300,
        url: "https://i.scdn.co/image/ab67616d00001e02e29a351729da4d29214e54e2",
        width: 300,
      },
      {
        height: 64,
        url: "https://i.scdn.co/image/ab67616d00004851e29a351729da4d29214e54e2",
        width: 64,
      },
    ],
    name: "Chinese Democracy",
    release_date: "2008-11-23",
    release_date_precision: "day",
    total_tracks: 14,
    type: "album",
    uri: "spotify:album:0suNLpB9xraAv1FcdlITjQ",
  },
  artists: [
    {
      external_urls: {
        spotify: "https://open.spotify.com/artist/3qm84nBOXUEQ2vnTfUTTFC",
      },
      href: "https://api.spotify.com/v1/artists/3qm84nBOXUEQ2vnTfUTTFC",
      id: "3qm84nBOXUEQ2vnTfUTTFC",
      name: "Guns N' Roses",
      type: "artist",
      uri: "spotify:artist:3qm84nBOXUEQ2vnTfUTTFC",
    },
  ],
  available_markets: [
    "AR",
    "AU",
    "AT",
    "BE",
    "BO",
    "BR",
    "BG",
    "CA",
    "CL",
    "CO",
    "CR",
    "CY",
    "CZ",
    "DK",
    "DO",
    "DE",
    "EC",
    "EE",
    "SV",
    "FI",
    "FR",
    "GR",
    "GT",
    "HN",
    "HK",
    "HU",
    "IS",
    "IE",
    "IT",
    "LV",
    "LT",
    "LU",
    "MY",
    "MT",
    "MX",
    "NL",
    "NZ",
    "NI",
    "NO",
    "PA",
    "PY",
    "PE",
    "PH",
    "PL",
    "PT",
    "SG",
    "SK",
    "ES",
    "SE",
    "CH",
    "TW",
    "TR",
    "UY",
    "US",
    "GB",
    "AD",
    "LI",
    "MC",
    "ID",
    "JP",
    "TH",
    "VN",
    "RO",
    "IL",
    "ZA",
    "SA",
    "AE",
    "BH",
    "QA",
    "OM",
    "KW",
    "EG",
    "MA",
    "DZ",
    "TN",
    "LB",
    "JO",
    "PS",
    "IN",
    "BY",
    "KZ",
    "MD",
    "UA",
    "AL",
    "BA",
    "HR",
    "ME",
    "MK",
    "RS",
    "SI",
    "KR",
    "BD",
    "PK",
    "LK",
    "GH",
    "KE",
    "NG",
    "TZ",
    "UG",
    "AG",
    "AM",
    "BS",
    "BB",
    "BZ",
    "BT",
    "BW",
    "BF",
    "CV",
    "CW",
    "DM",
    "FJ",
    "GM",
    "GE",
    "GD",
    "GW",
    "GY",
    "HT",
    "JM",
    "KI",
    "LS",
    "LR",
    "MW",
    "MV",
    "ML",
    "MH",
    "FM",
    "NA",
    "NR",
    "NE",
    "PW",
    "PG",
    "WS",
    "SM",
    "ST",
    "SN",
    "SC",
    "SL",
    "SB",
    "KN",
    "LC",
    "VC",
    "SR",
    "TL",
    "TO",
    "TT",
    "TV",
    "VU",
    "AZ",
    "BN",
    "BI",
    "KH",
    "CM",
    "TD",
    "KM",
    "GQ",
    "SZ",
    "GA",
    "GN",
    "KG",
    "LA",
    "MO",
    "MR",
    "MN",
    "NP",
    "RW",
    "TG",
    "UZ",
    "ZW",
    "BJ",
    "MG",
    "MU",
    "MZ",
    "AO",
    "CI",
    "DJ",
    "ZM",
    "CD",
    "CG",
    "IQ",
    "LY",
    "TJ",
    "VE",
    "ET",
    "XK",
  ],
  disc_number: 1,
  duration_ms: 334373,
  explicit: false,
  external_ids: {
    isrc: "USUM70842911",
  },
  external_urls: {
    spotify: "https://open.spotify.com/track/2FEWcWHnDmGD6WSqpW4VYu",
  },
  href: "https://api.spotify.com/v1/tracks/2FEWcWHnDmGD6WSqpW4VYu",
  id: "2FEWcWHnDmGD6WSqpW4VYu",
  is_local: false,
  name: "This I Love",
  popularity: 69,
  preview_url: null,
  track_number: 13,
  type: "track",
  uri: "spotify:track:2FEWcWHnDmGD6WSqpW4VYu",
};
const initialSong2Data = {
  album: {
    album_type: "album",
    artists: [
      {
        external_urls: {
          spotify: "https://open.spotify.com/artist/23APOVagRCKlVE9eGuRUpa",
        },
        href: "https://api.spotify.com/v1/artists/23APOVagRCKlVE9eGuRUpa",
        id: "23APOVagRCKlVE9eGuRUpa",
        name: "Hasan Mutlucan",
        type: "artist",
        uri: "spotify:artist:23APOVagRCKlVE9eGuRUpa",
      },
    ],
    available_markets: [
      "AR",
      "AU",
      "AT",
      "BE",
      "BO",
      "BR",
      "BG",
      "CA",
      "CL",
      "CO",
      "CR",
      "CY",
      "CZ",
      "DK",
      "DO",
      "DE",
      "EC",
      "EE",
      "SV",
      "FI",
      "FR",
      "GR",
      "GT",
      "HN",
      "HK",
      "HU",
      "IS",
      "IE",
      "IT",
      "LV",
      "LT",
      "LU",
      "MY",
      "MT",
      "MX",
      "NL",
      "NZ",
      "NI",
      "NO",
      "PA",
      "PY",
      "PE",
      "PH",
      "PL",
      "PT",
      "SG",
      "SK",
      "ES",
      "SE",
      "CH",
      "TW",
      "TR",
      "UY",
      "US",
      "GB",
      "AD",
      "LI",
      "MC",
      "ID",
      "JP",
      "TH",
      "VN",
      "RO",
      "IL",
      "ZA",
      "SA",
      "AE",
      "BH",
      "QA",
      "OM",
      "KW",
      "EG",
      "MA",
      "DZ",
      "TN",
      "LB",
      "JO",
      "PS",
      "IN",
      "BY",
      "KZ",
      "MD",
      "UA",
      "AL",
      "BA",
      "HR",
      "ME",
      "MK",
      "RS",
      "SI",
      "KR",
      "BD",
      "PK",
      "LK",
      "GH",
      "KE",
      "NG",
      "TZ",
      "UG",
      "AG",
      "AM",
      "BS",
      "BB",
      "BZ",
      "BT",
      "BW",
      "BF",
      "CV",
      "CW",
      "DM",
      "FJ",
      "GM",
      "GE",
      "GD",
      "GW",
      "GY",
      "HT",
      "JM",
      "KI",
      "LS",
      "LR",
      "MW",
      "MV",
      "ML",
      "MH",
      "FM",
      "NA",
      "NR",
      "NE",
      "PW",
      "PG",
      "WS",
      "SM",
      "ST",
      "SN",
      "SC",
      "SL",
      "SB",
      "KN",
      "LC",
      "VC",
      "SR",
      "TL",
      "TO",
      "TT",
      "TV",
      "VU",
      "AZ",
      "BN",
      "BI",
      "KH",
      "CM",
      "TD",
      "KM",
      "GQ",
      "SZ",
      "GA",
      "GN",
      "KG",
      "LA",
      "MO",
      "MR",
      "MN",
      "NP",
      "RW",
      "TG",
      "UZ",
      "ZW",
      "BJ",
      "MG",
      "MU",
      "MZ",
      "AO",
      "CI",
      "DJ",
      "ZM",
      "CD",
      "CG",
      "IQ",
      "LY",
      "TJ",
      "VE",
      "ET",
      "XK",
    ],
    external_urls: {
      spotify: "https://open.spotify.com/album/6tRBb76V7DeMfcnLwxaJrL",
    },
    href: "https://api.spotify.com/v1/albums/6tRBb76V7DeMfcnLwxaJrL",
    id: "6tRBb76V7DeMfcnLwxaJrL",
    images: [
      {
        height: 640,
        url: "https://i.scdn.co/image/ab67616d0000b273b379be6d51e44b9f8041c382",
        width: 640,
      },
      {
        height: 300,
        url: "https://i.scdn.co/image/ab67616d00001e02b379be6d51e44b9f8041c382",
        width: 300,
      },
      {
        height: 64,
        url: "https://i.scdn.co/image/ab67616d00004851b379be6d51e44b9f8041c382",
        width: 64,
      },
    ],
    name: "Kahramanlik Turkuleri",
    release_date: "1974-01-01",
    release_date_precision: "day",
    total_tracks: 12,
    type: "album",
    uri: "spotify:album:6tRBb76V7DeMfcnLwxaJrL",
  },
  artists: [
    {
      external_urls: {
        spotify: "https://open.spotify.com/artist/23APOVagRCKlVE9eGuRUpa",
      },
      href: "https://api.spotify.com/v1/artists/23APOVagRCKlVE9eGuRUpa",
      id: "23APOVagRCKlVE9eGuRUpa",
      name: "Hasan Mutlucan",
      type: "artist",
      uri: "spotify:artist:23APOVagRCKlVE9eGuRUpa",
    },
  ],
  available_markets: [
    "AR",
    "AU",
    "AT",
    "BE",
    "BO",
    "BR",
    "BG",
    "CA",
    "CL",
    "CO",
    "CR",
    "CY",
    "CZ",
    "DK",
    "DO",
    "DE",
    "EC",
    "EE",
    "SV",
    "FI",
    "FR",
    "GR",
    "GT",
    "HN",
    "HK",
    "HU",
    "IS",
    "IE",
    "IT",
    "LV",
    "LT",
    "LU",
    "MY",
    "MT",
    "MX",
    "NL",
    "NZ",
    "NI",
    "NO",
    "PA",
    "PY",
    "PE",
    "PH",
    "PL",
    "PT",
    "SG",
    "SK",
    "ES",
    "SE",
    "CH",
    "TW",
    "TR",
    "UY",
    "US",
    "GB",
    "AD",
    "LI",
    "MC",
    "ID",
    "JP",
    "TH",
    "VN",
    "RO",
    "IL",
    "ZA",
    "SA",
    "AE",
    "BH",
    "QA",
    "OM",
    "KW",
    "EG",
    "MA",
    "DZ",
    "TN",
    "LB",
    "JO",
    "PS",
    "IN",
    "BY",
    "KZ",
    "MD",
    "UA",
    "AL",
    "BA",
    "HR",
    "ME",
    "MK",
    "RS",
    "SI",
    "KR",
    "BD",
    "PK",
    "LK",
    "GH",
    "KE",
    "NG",
    "TZ",
    "UG",
    "AG",
    "AM",
    "BS",
    "BB",
    "BZ",
    "BT",
    "BW",
    "BF",
    "CV",
    "CW",
    "DM",
    "FJ",
    "GM",
    "GE",
    "GD",
    "GW",
    "GY",
    "HT",
    "JM",
    "KI",
    "LS",
    "LR",
    "MW",
    "MV",
    "ML",
    "MH",
    "FM",
    "NA",
    "NR",
    "NE",
    "PW",
    "PG",
    "WS",
    "SM",
    "ST",
    "SN",
    "SC",
    "SL",
    "SB",
    "KN",
    "LC",
    "VC",
    "SR",
    "TL",
    "TO",
    "TT",
    "TV",
    "VU",
    "AZ",
    "BN",
    "BI",
    "KH",
    "CM",
    "TD",
    "KM",
    "GQ",
    "SZ",
    "GA",
    "GN",
    "KG",
    "LA",
    "MO",
    "MR",
    "MN",
    "NP",
    "RW",
    "TG",
    "UZ",
    "ZW",
    "BJ",
    "MG",
    "MU",
    "MZ",
    "AO",
    "CI",
    "DJ",
    "ZM",
    "CD",
    "CG",
    "IQ",
    "LY",
    "TJ",
    "VE",
    "ET",
    "XK",
  ],
  disc_number: 1,
  duration_ms: 165558,
  explicit: false,
  external_ids: {
    isrc: "TRAAA9300622",
  },
  external_urls: {
    spotify: "https://open.spotify.com/track/6nmkGJq7wrk0hjOIhCkRl7",
  },
  href: "https://api.spotify.com/v1/tracks/6nmkGJq7wrk0hjOIhCkRl7",
  id: "6nmkGJq7wrk0hjOIhCkRl7",
  is_local: false,
  name: "Kuffar",
  popularity: 36,
  preview_url: null,
  track_number: 6,
  type: "track",
  uri: "spotify:track:6nmkGJq7wrk0hjOIhCkRl7",
};

function SongProvider({ children }) {
  const [accessToken, setAccessToken] = useState();
  const [searchQuery, setSearchQuery] = useState();
  const [searchedSongs, setSearchedSongs] = useState();
  const [song1, setSong1] = useState(initialSong1Data);
  const [song2, setSong2] = useState(initialSong2Data);
  const [isSpotifyLoading, setIsSpotifyLoading] = useState(false);

  function setSongs(currentSong, song) {
    if (currentSong == 1) setSong1(song);
    if (currentSong == 2) setSong2(song);
  }

  async function getSongs(searchQuery) {
    const searchParameters = {
      method: "GET",
      headers: {
        "Content-Type": "application/json",
        Authorization: "Bearer " + accessToken,
      },
    };

    setIsSpotifyLoading(true);
    setSearchedSongs(null);
    const res = await fetch(
      `https://api.spotify.com/v1/search?q=${searchQuery}&type=track&limit=5&offset=0`,
      searchParameters
    );
    const data = await res.json();
    console.log(data.tracks.items);
    setSearchedSongs(data.tracks.items);
    setIsSpotifyLoading(false);
  }

  return (
    <SongContext.Provider
      value={{
        setAccessToken,
        searchQuery,
        setSearchQuery,
        getSongs,
        searchedSongs,
        setSearchedSongs,
        song1,
        setSong1,
        song2,
        setSong2,
        setSongs,
        isSpotifyLoading,
        setIsSpotifyLoading,
      }}
    >
      {children}
    </SongContext.Provider>
  );
}

function useSongs() {
  const context = useContext(SongContext);
  return context;
}

export { SongProvider, useSongs };
